// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  blog: create.doc("blog", {"dont-use-shadcn.mdx": () => import("../src/content/blog/dont-use-shadcn.mdx?collection=blog"), "jakarta-transportation/krl-bogor.mdx": () => import("../src/content/blog/jakarta-transportation/krl-bogor.mdx?collection=blog"), "jakarta-transportation/krl-tanjung-priok.mdx": () => import("../src/content/blog/jakarta-transportation/krl-tanjung-priok.mdx?collection=blog"), "jakarta-transportation/krl-cikarang-loop.mdx": () => import("../src/content/blog/jakarta-transportation/krl-cikarang-loop.mdx?collection=blog"), "jakarta-transportation/mrt-north-south-2a.mdx": () => import("../src/content/blog/jakarta-transportation/mrt-north-south-2a.mdx?collection=blog"), "jakarta-transportation/mrt-north-south-2b.mdx": () => import("../src/content/blog/jakarta-transportation/mrt-north-south-2b.mdx?collection=blog"), "jakarta-transportation/index.mdx": () => import("../src/content/blog/jakarta-transportation/index.mdx?collection=blog"), "jakarta-transportation/krl-rangkasbitung.mdx": () => import("../src/content/blog/jakarta-transportation/krl-rangkasbitung.mdx?collection=blog"), "jakarta-transportation/mrt-east-west-3.mdx": () => import("../src/content/blog/jakarta-transportation/mrt-east-west-3.mdx?collection=blog"), "jakarta-transportation/krl-tangerang.mdx": () => import("../src/content/blog/jakarta-transportation/krl-tangerang.mdx?collection=blog"), "jakarta-transportation/mrt-north-south-1.mdx": () => import("../src/content/blog/jakarta-transportation/mrt-north-south-1.mdx?collection=blog"), }),
  labs: create.doc("labs", {"(root)/get-started.mdx": () => import("../src/content/labs/(root)/get-started.mdx?collection=labs"), "(root)/changelog.mdx": () => import("../src/content/labs/(root)/changelog.mdx?collection=labs"), "(root)/components.mdx": () => import("../src/content/labs/(root)/components.mdx?collection=labs"), "components/trailing-scroll.mdx": () => import("../src/content/labs/components/trailing-scroll.mdx?collection=labs"), "components/button.mdx": () => import("../src/content/labs/components/button.mdx?collection=labs"), "components/card-overlap-scroll.mdx": () => import("../src/content/labs/components/card-overlap-scroll.mdx?collection=labs"), "components/parallax-scroll.mdx": () => import("../src/content/labs/components/parallax-scroll.mdx?collection=labs"), "components/card-stack-scroll.mdx": () => import("../src/content/labs/components/card-stack-scroll.mdx?collection=labs"), "components/rotate-velocity-scroll.mdx": () => import("../src/content/labs/components/rotate-velocity-scroll.mdx?collection=labs"), "components/smooth-cursor.mdx": () => import("../src/content/labs/components/smooth-cursor.mdx?collection=labs"), }),
};
export default browserCollections;