// @ts-nocheck
import { frontmatter as __fd_glob_20 } from "../src/content/labs/components/trailing-scroll.mdx?collection=labs&only=frontmatter"
import { frontmatter as __fd_glob_19 } from "../src/content/labs/components/smooth-cursor.mdx?collection=labs&only=frontmatter"
import { frontmatter as __fd_glob_18 } from "../src/content/labs/components/rotate-velocity-scroll.mdx?collection=labs&only=frontmatter"
import { frontmatter as __fd_glob_17 } from "../src/content/labs/components/parallax-scroll.mdx?collection=labs&only=frontmatter"
import { frontmatter as __fd_glob_16 } from "../src/content/labs/components/card-stack-scroll.mdx?collection=labs&only=frontmatter"
import { frontmatter as __fd_glob_15 } from "../src/content/labs/components/card-overlap-scroll.mdx?collection=labs&only=frontmatter"
import { frontmatter as __fd_glob_14 } from "../src/content/labs/components/button.mdx?collection=labs&only=frontmatter"
import { frontmatter as __fd_glob_13 } from "../src/content/labs/(root)/get-started.mdx?collection=labs&only=frontmatter"
import { frontmatter as __fd_glob_12 } from "../src/content/labs/(root)/components.mdx?collection=labs&only=frontmatter"
import { frontmatter as __fd_glob_11 } from "../src/content/labs/(root)/changelog.mdx?collection=labs&only=frontmatter"
import { frontmatter as __fd_glob_10 } from "../src/content/blog/jakarta-transportation/mrt-north-south-2b.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_9 } from "../src/content/blog/jakarta-transportation/mrt-north-south-2a.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_8 } from "../src/content/blog/jakarta-transportation/mrt-north-south-1.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_7 } from "../src/content/blog/jakarta-transportation/mrt-east-west-3.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_6 } from "../src/content/blog/jakarta-transportation/krl-tanjung-priok.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_5 } from "../src/content/blog/jakarta-transportation/krl-tangerang.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_4 } from "../src/content/blog/jakarta-transportation/krl-rangkasbitung.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_3 } from "../src/content/blog/jakarta-transportation/krl-cikarang-loop.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_2 } from "../src/content/blog/jakarta-transportation/krl-bogor.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_1 } from "../src/content/blog/jakarta-transportation/index.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_0 } from "../src/content/blog/dont-use-shadcn.mdx?collection=blog&only=frontmatter"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const blog = await create.docLazy("blog", "src/content/blog", {"dont-use-shadcn.mdx": __fd_glob_0, "jakarta-transportation/index.mdx": __fd_glob_1, "jakarta-transportation/krl-bogor.mdx": __fd_glob_2, "jakarta-transportation/krl-cikarang-loop.mdx": __fd_glob_3, "jakarta-transportation/krl-rangkasbitung.mdx": __fd_glob_4, "jakarta-transportation/krl-tangerang.mdx": __fd_glob_5, "jakarta-transportation/krl-tanjung-priok.mdx": __fd_glob_6, "jakarta-transportation/mrt-east-west-3.mdx": __fd_glob_7, "jakarta-transportation/mrt-north-south-1.mdx": __fd_glob_8, "jakarta-transportation/mrt-north-south-2a.mdx": __fd_glob_9, "jakarta-transportation/mrt-north-south-2b.mdx": __fd_glob_10, }, {"dont-use-shadcn.mdx": () => import("../src/content/blog/dont-use-shadcn.mdx?collection=blog"), "jakarta-transportation/index.mdx": () => import("../src/content/blog/jakarta-transportation/index.mdx?collection=blog"), "jakarta-transportation/krl-bogor.mdx": () => import("../src/content/blog/jakarta-transportation/krl-bogor.mdx?collection=blog"), "jakarta-transportation/krl-cikarang-loop.mdx": () => import("../src/content/blog/jakarta-transportation/krl-cikarang-loop.mdx?collection=blog"), "jakarta-transportation/krl-rangkasbitung.mdx": () => import("../src/content/blog/jakarta-transportation/krl-rangkasbitung.mdx?collection=blog"), "jakarta-transportation/krl-tangerang.mdx": () => import("../src/content/blog/jakarta-transportation/krl-tangerang.mdx?collection=blog"), "jakarta-transportation/krl-tanjung-priok.mdx": () => import("../src/content/blog/jakarta-transportation/krl-tanjung-priok.mdx?collection=blog"), "jakarta-transportation/mrt-east-west-3.mdx": () => import("../src/content/blog/jakarta-transportation/mrt-east-west-3.mdx?collection=blog"), "jakarta-transportation/mrt-north-south-1.mdx": () => import("../src/content/blog/jakarta-transportation/mrt-north-south-1.mdx?collection=blog"), "jakarta-transportation/mrt-north-south-2a.mdx": () => import("../src/content/blog/jakarta-transportation/mrt-north-south-2a.mdx?collection=blog"), "jakarta-transportation/mrt-north-south-2b.mdx": () => import("../src/content/blog/jakarta-transportation/mrt-north-south-2b.mdx?collection=blog"), });

export const labs = await create.docsLazy("labs", "src/content/labs", {}, {"(root)/changelog.mdx": __fd_glob_11, "(root)/components.mdx": __fd_glob_12, "(root)/get-started.mdx": __fd_glob_13, "components/button.mdx": __fd_glob_14, "components/card-overlap-scroll.mdx": __fd_glob_15, "components/card-stack-scroll.mdx": __fd_glob_16, "components/parallax-scroll.mdx": __fd_glob_17, "components/rotate-velocity-scroll.mdx": __fd_glob_18, "components/smooth-cursor.mdx": __fd_glob_19, "components/trailing-scroll.mdx": __fd_glob_20, }, {"(root)/changelog.mdx": () => import("../src/content/labs/(root)/changelog.mdx?collection=labs"), "(root)/components.mdx": () => import("../src/content/labs/(root)/components.mdx?collection=labs"), "(root)/get-started.mdx": () => import("../src/content/labs/(root)/get-started.mdx?collection=labs"), "components/button.mdx": () => import("../src/content/labs/components/button.mdx?collection=labs"), "components/card-overlap-scroll.mdx": () => import("../src/content/labs/components/card-overlap-scroll.mdx?collection=labs"), "components/card-stack-scroll.mdx": () => import("../src/content/labs/components/card-stack-scroll.mdx?collection=labs"), "components/parallax-scroll.mdx": () => import("../src/content/labs/components/parallax-scroll.mdx?collection=labs"), "components/rotate-velocity-scroll.mdx": () => import("../src/content/labs/components/rotate-velocity-scroll.mdx?collection=labs"), "components/smooth-cursor.mdx": () => import("../src/content/labs/components/smooth-cursor.mdx?collection=labs"), "components/trailing-scroll.mdx": () => import("../src/content/labs/components/trailing-scroll.mdx?collection=labs"), });