// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";
import type { RegistryEntry as RegistryEntryType } from "./schema";

export const Index: Record<string, RegistryEntryType> = {
  "button": {
    name: "button",
    description: "A cool interactive button component",
    type: "registry:component",
    registryDependencies: [],
    files: [{
        path: "labs-registry/components-v1/button.tsx",
        type: "registry:component",
        target: ""
      }],
    component: React.lazy(async () => {
        const mod = await import("@/labs-registry/components-v1/button") as any
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "button"
        return { default: mod.default || mod[exportName] }
      }),
    categories: ["interactive"],
    meta: {},
  },
  "card-overlap-scroll": {
    name: "card-overlap-scroll",
    description: "Cards that overlap on scroll",
    type: "registry:component",
    registryDependencies: [],
    files: [{
        path: "labs-registry/components-v1/card-overlap-scroll.tsx",
        type: "registry:component",
        target: ""
      }],
    component: React.lazy(async () => {
        const mod = await import("@/labs-registry/components-v1/card-overlap-scroll") as any
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "card-overlap-scroll"
        return { default: mod.default || mod[exportName] }
      }),
    categories: ["scroll","cards"],
    meta: {},
  },
  "card-stack-scroll": {
    name: "card-stack-scroll",
    description: "Stacked cards with scroll effects",
    type: "registry:component",
    registryDependencies: [],
    files: [{
        path: "labs-registry/components-v1/card-stack-scroll.tsx",
        type: "registry:component",
        target: ""
      }],
    component: React.lazy(async () => {
        const mod = await import("@/labs-registry/components-v1/card-stack-scroll") as any
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "card-stack-scroll"
        return { default: mod.default || mod[exportName] }
      }),
    categories: ["scroll","cards"],
    meta: {},
  },
  "parallax-scroll": {
    name: "parallax-scroll",
    description: "Parallax scrolling effect",
    type: "registry:component",
    registryDependencies: [],
    files: [{
        path: "labs-registry/components-v1/parallax-scroll.tsx",
        type: "registry:component",
        target: ""
      }],
    component: React.lazy(async () => {
        const mod = await import("@/labs-registry/components-v1/parallax-scroll") as any
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "parallax-scroll"
        return { default: mod.default || mod[exportName] }
      }),
    categories: ["scroll","effects"],
    meta: {},
  },
  "rotate-velocity-scroll": {
    name: "rotate-velocity-scroll",
    description: "Rotation based on scroll velocity",
    type: "registry:component",
    registryDependencies: [],
    files: [{
        path: "labs-registry/components-v1/rotate-velocity-scroll.tsx",
        type: "registry:component",
        target: ""
      }],
    component: React.lazy(async () => {
        const mod = await import("@/labs-registry/components-v1/rotate-velocity-scroll") as any
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "rotate-velocity-scroll"
        return { default: mod.default || mod[exportName] }
      }),
    categories: ["scroll","effects"],
    meta: {},
  },
  "smooth-cursor": {
    name: "smooth-cursor",
    description: "Smooth cursor following effect",
    type: "registry:component",
    registryDependencies: [],
    files: [{
        path: "labs-registry/components-v1/smooth-cursor.tsx",
        type: "registry:component",
        target: ""
      }],
    component: React.lazy(async () => {
        const mod = await import("@/labs-registry/components-v1/smooth-cursor") as any
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "smooth-cursor"
        return { default: mod.default || mod[exportName] }
      }),
    categories: ["cursor","effects"],
    meta: {},
  },
  "trailing-scroll": {
    name: "trailing-scroll",
    description: "Trailing effect on scroll",
    type: "registry:component",
    registryDependencies: [],
    files: [{
        path: "labs-registry/components-v1/trailing-scroll.tsx",
        type: "registry:component",
        target: ""
      }],
    component: React.lazy(async () => {
        const mod = await import("@/labs-registry/components-v1/trailing-scroll") as any
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "trailing-scroll"
        return { default: mod.default || mod[exportName] }
      }),
    categories: ["scroll","effects"],
    meta: {},
  },
};

export type RegistryEntry = keyof typeof Index;
