// This file is kept for backward compatibility but is no longer manually maintained.
// The registry is now auto-generated by scripts/build-registry.ts
// Run `bun run build:registry` to regenerate the registry from component files.
//
// The script automatically:
// - Scans src/labs-registry/components-v1/ for component files
// - Extracts descriptions from src/content/labs/components/*.mdx files
// - Categorizes components based on naming patterns
// - Processes demo files from the demo/ subdirectory
//
// To add a new component:
// 1. Create the component file in src/labs-registry/components-v1/
// 2. Create the documentation in src/content/labs/components/
// 3. Run `bun run build:registry`

import type { Registry } from "./schema";

export const registry: Registry = {
  items: [],
};
