import type { Registry } from "./schema";

export const registry: Registry = {
  items: [
    {
      name: "button",
      description: "A cool interactive button component",
      type: "registry:component",
      files: ["button.tsx"],
      dependencies: [],
      registryDependencies: [],
      categories: ["interactive"],
    },
    {
      name: "demo-button",
      description: "Demo of the button component",
      type: "registry:example",
      files: ["demo/button.tsx"],
      dependencies: [],
      registryDependencies: ["button"],
      categories: ["interactive"],
    },
    {
      name: "demo-smooth-cursor",
      description: "Demo of the smooth-cursor component",
      type: "registry:example",
      files: ["demo/smooth-cursor.tsx"],
      dependencies: [],
      registryDependencies: ["button"],
      categories: ["interactive"],
    },
    {
      name: "card-overlap-scroll",
      description: "Cards that overlap on scroll",
      type: "registry:component",
      files: ["card-overlap-scroll.tsx"],
      dependencies: [],
      registryDependencies: [],
      categories: ["scroll", "cards"],
    },
    {
      name: "card-stack-scroll",
      description: "Stacked cards with scroll effects",
      type: "registry:component",
      files: ["card-stack-scroll.tsx"],
      dependencies: [],
      registryDependencies: [],
      categories: ["scroll", "cards"],
    },
    {
      name: "parallax-scroll",
      description: "Parallax scrolling effect",
      type: "registry:component",
      files: ["parallax-scroll.tsx"],
      dependencies: [],
      registryDependencies: [],
      categories: ["scroll", "effects"],
    },
    {
      name: "rotate-velocity-scroll",
      description: "Rotation based on scroll velocity",
      type: "registry:component",
      files: ["rotate-velocity-scroll.tsx"],
      dependencies: [],
      registryDependencies: [],
      categories: ["scroll", "effects"],
    },
    {
      name: "smooth-cursor",
      description: "Smooth cursor following effect",
      type: "registry:component",
      files: ["smooth-cursor.tsx"],
      dependencies: [],
      registryDependencies: [],
      categories: ["cursor", "effects"],
    },
    {
      name: "trailing-scroll",
      description: "Trailing effect on scroll",
      type: "registry:component",
      files: ["trailing-scroll.tsx"],
      dependencies: [],
      registryDependencies: [],
      categories: ["scroll", "effects"],
    },
  ],
};
